###################################################################################################
# You can change the values as you want but be careful, some of them can make text display weird, #
# to prevent you, I will put a /warning\ above settings that require attention                    #
###################################################################################################

####################################################################
# Never change the files values in the "guilds" folder             #
# otherwise the plugin may no longer work, let it do the job alone #
####################################################################

####################################################
# If you make any changes while server is running, #
# don't forget to save and reload                  #
####################################################

infos:
  plugin-prefix: "ยง7[ยงd#ยง7] "

chat:
  # If you don't want the chat format "[guild] [displayname] message" that the plugin puts,
  # you can set this to true to disable it
  disable-format: false

guilds:
  min-length-name: 3
  # /warning\
  max-length-name: 15
  max-members: 10
  exp:
    # You can change the amount of exp gained from events
    kill-player: 5
    kill-mob: 3
  pvp:
    # When a player kills a player from another guild, their will be a lighting effect on the dead player,
    # you can disable it by set this to false
    lightning-effect: true
    # Set this to false if you don't want the special kill message
    kill-message: true
