name: NewGuilds
version: 0.1
main: no.tytraman.newguilds.NewGuilds
api-version: 1.13
author: Tytraman

commands:
  guild:
    description: "Command to manage guilds"
    permission: no.newguilds.guild
    permission-message: "Sorry, but you can't do that"
    usage: "/guild"

