name: NewGuilds
version: 0.2
main: no.tytraman.newguilds.NewGuilds
api-version: 1.13
author: Tytraman

commands:
  guild:
    description: "Command to manage guilds"
    permission: no.newguilds.guild
    permission-message: "Désolé, mais tu ne peux pas faire ça..."
    usage: "/guild"

